language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=Locale
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2.4
  matrix:
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5
    - DB=mysql CAKE_VERSION=2.6

before_install:
  - composer self-update
  - sudo locale-gen --no-purge --lang pt_BR.UTF-8
  - composer global require 'phpunit/phpunit=3.7.33'
  - ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ./Vendor/PHPUnit
  - phpenv rehash

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - git clone -b $CAKE_VERSION git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - cp -R ../locale app/Plugin/Locale
  - echo "setlocale(LC_ALL, 'pt_BR.utf8', 'pt_BR', 'pt-br', 'portuguese');
    " >> ./app/Config/bootstrap.php
  - echo "CakePlugin::loadAll(array(array('bootstrap' => true, 'routes' => true, 'ignoreMissing' => true)));" >> Config/bootstrap.php
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    }" > ./app/Config/database.php

script:
  - ./lib/Cake/Console/cake test Locale AllLocaleTests

notifications:
  email: false
